const SERVICE_CATEGORIES = {
    COLORING: "COLORING",
    HAIRCUT: "HAIRCUT",
    BEARD: "BEARD",
    STYLING: "STYLING",
    TREATMENT: "TREATMENT",
    EXTENSIONS: "EXTENSIONS",
    SPECIAL_COMBO: "SPECIAL_COMBO"
}

const SERVICE_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    DISCONTINUED: "DISCONTINUED"
}

const USER_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED"
}

const USER_ROLES = {
    ADMIN: "ADMIN",
    CUSTOMER: "CUSTOMER",
    STAFF: "STAFF",
}

const BOOKING_STATUS = {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED"
}

const PROMOTION_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    EXPIRED: "EXPIRED"
}

const PAYMENT_METHODS = {
    CASH: "CASH",
    BANKING: "BANKING",
}

module.exports = {
    SERVICE_CATEGORIES,
    USER_STATUS,
    USER_ROLES,
    BOOKING_STATUS,
    SERVICE_STATUS,
    PROMOTION_STATUS,
    PAYMENT_METHODS
}